#!/bin/bash

# Source git completetions
. /usr/share/bash-completion/completions/git

alias gs='git status'
__git_complete gs _git_status

alias gcmm='git commit -m'
__git_complete gcmm _git_commit

alias gaa='git add -A'
__git_complete gaa _git_add
